### ISSUE TITLE
Fatal error: Error occured: connect ECONNREFUSED 127.0.0.1:25

### ISSUE THREAD

**Issue by sashberd** [dwightjack/grunt-nodemailer#19]
After I`d updated to version 1.0.0.0
I got next error each time
Fatal error: Error occured: connect ECONNREFUSED 127.0.0.1:25

I revert to 0.3.0, the problem was fixed.

Is there any global problem or I should change something in my settings or properties

**Comment by dwightjack** [comment]
Hi can you post the task configuration object?

**Comment by DrChills** [comment]
I've had the same, installed 0.3.0 and everything is fine... here's the config:

```
nodemailer: {
			options: {
				transport: {
					type: 'SMTP',
					options: {
						service: 'Gmail',
						auth: {
							name: 'b2g test email',
							user: 'b2gtestemail@gmail.com',
							pass: 'donkeycheeks1'
						}
					}
				},
				recipients: '<%= emailadds %>'
			},
			dist: {
				src: ['email-templates/dist/*.html']
			}
		},
```

Windows 10 - if that helps!

**Comment by dwightjack** [comment]
Hi I've updated the plugin to Nodemailer 2.x in version 1.1.0 (https://github.com/dwightjack/grunt-nodemailer/releases/tag/1.1.0)

Let me know if that fixes the bug

**Comment by sashberd** [comment]
Sorry for such huge delay. Was not on this company project. The issue is still exists event with version 2.x.

**Comment by sashberd** [comment]
![untitled](https://cloud.githubusercontent.com/assets/11975561/17461726/dded047a-5c9e-11e6-858c-3b769cd5da27.png)
This is how it looks like

**Comment by StevenX911** [comment]
Let me know if that fixes the bug

**Comment by askdesigners** [comment]
it's 2018 and I still get this error ;)

**Comment by KevsRepos** [comment]
Its 2021 and the error is still there!

**Comment by dwightjack** [comment]
@KevsRepos as I wrote on the project's readme, I am not longer maintaining this project. Feel free to contribute with a PR to fix this issue.
